/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
But optimized for your specific 'orb.glb' file
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Orb(props) {
  const group = useRef();
  // Load the model and its animations
  const { scene, animations } = useGLTF('/orb.glb');
  // Hook to manage animations
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // "Take 001" is the animation name found in your file
    const action = actions['Take 001'];
    
    if (action) {
      action.play(); // Auto-play the animation
    } else {
        console.warn('Animation "Take 001" not found');
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Renders the full scene from the GLB */}
      <primitive object={scene} />
    </group>
  );
}

// Preload to avoid loading delay
useGLTF.preload('/orb.glb');